services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Domain\User\ReferenceProvider\:
        resource: '../../src/Domain/User/ReferenceProvider/*'
