imports:
    - { resource: services/ }

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: "%kernel.project_dir%"
            $dataFixtureDir: "%kernel.project_dir%/tests/DataFixtures"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/'
        exclude:
            - '../src/Application/*/Entity/'
            - '../src/Application/Traits/'
            - '../src/Application/*/ReferenceProvider/'
            - '../src/Application/*/Factory/'
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/ReferenceProvider/'
            - '../src/Domain/*/Factory/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Application\Common\Manager\JwtPayloadManager:
        public: true
    
    App\Application\Common\Data\DataLoader:
        public: true
        arguments:
            $fixtureLoader: '@?fidry_alice_data_fixtures.loader.doctrine'

    fidry_alice_data_fixtures.persistence.purger_factory.doctrine:
        class: App\Application\Common\Data\Purger
        arguments:
            - '@doctrine.orm.entity_manager'
